# Travis-CI Build for tracking
# see travis-ci.org for details

language: c

# Make sure CMake is installed
install:
 - sudo apt-get install build-essentials

# Build mono from source, build the project, and run tests
script:
 - git clone https://github.com/inorton/mono-ubuntu-build.git
 - source mono_env /opt/mono
 - bash build_mono
# - xbuild CI-build.msbuild /t:Deploy

# Only watch the development branch
branches:
 only:
   - master
